repos:
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        args:
          - --safe
          - --quiet
        files: ^((pydeconz|tests)/.+)?[^/]+\.py$
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.7.9
#     hooks:
#     -   id: flake8
#         additional_dependencies:
#           - flake8-docstrings==1.5.0
#           - pydocstyle==4.0.1
#         files: ^(pydeconz|tests)/.+\.py$