[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
known_first_party = ["pydeconz", "tests"]
forced_separate = ["tests"]
combine_as_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.ruff]
target-version = "py310"
select = [
    "RUF006", # Store a reference to the return value of asyncio.create_task
]
