[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.ruff]
src = ["pydeconz", "tests"]
target-version = "py310"
select = [
    "I",  # isort
    "RUF006", # Store a reference to the return value of asyncio.create_task
]

[tool.ruff.isort]
 force-sort-within-sections = true
 known-first-party = ["pydeconz"]
 combine-as-imports = true
 split-on-trailing-comma = false