# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install ".[requirements, requirements_test]"
      - name: Check lint with Ruff
        run: |
          ruff check pydeconz tests
      - name: Check formatting with ruff
        run: |
          ruff format --check pydeconz tests
      - name: Check typing with mypy
        run: |
          mypy pydeconz
      - name: Test with pytest
        run: |
          pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=pydeconz --cov-report=xml --cov-report=html
